# Generated by Django 3.2.23 on 2024-02-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_image_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='supported_teams_choices',
            field=models.CharField(choices=[('LIVERPOOL', 'Liverpool'), ('EVERTON', 'Everton'), ('CHELSEA', 'Chelsea'), ('MAN_CITY', 'Man City'), ('SELECT_TEAM', 'Select team'), ('MAN_UTD', 'Manchester Utd'), ('TOTTENHAM_HOTSPUR', 'Tottenham Hotspur'), ('WOLVERHAMPTON_WANDERERS', 'Wolverhampton Wanderers'), ('FULHAM', 'Fulham'), ('ARSENAL', 'Arsenal'), ('BRENTFORD', 'Brentford'), ('WEST_HAM_UTD', 'West Ham Utd'), ('BOURNEMOUTH_AFC', 'Bournemouth AFC'), ('ASTON_VILLA', 'Aston Villa'), ('NOTTINGHAM_FOREST', 'Nottingham Forest'), ('LUTON_TOWN', 'Luton Town'), ('NEWCASTLE_UTD', 'Newcastle Utd'), ('CRYSTAL_PALACE', 'Crystal Palace'), ('BRIGHTON_&_HOVE_ALBION', 'Brighton & Hove Albion'), ('SHEFFIELD_UTD', 'Sheffield Utd'), ('BURNLEY', 'Burnley')], default='SELECT_TEAM', max_length=24),
        ),
    ]
