# Generated by Django 3.2.23 on 2024-02-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supported', '0003_remove_teamslist_league'),
        ('posts', '0004_post_supported_teams_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='supported_teams_choices',
        ),
        migrations.AddField(
            model_name='post',
            name='supported_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supported.teamslist'),
        ),
    ]
