# Generated by Django 3.2.23 on 2024-02-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_supported_teams_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='supported_teams_choices',
            field=models.CharField(choices=[('ARSENAL', 'Arsenal'), ('ASTON_VILLA', 'Aston Villa'), ('BOURNEMOUTH_AFC', 'Bournemouth AFC'), ('BRENTFORD', 'Brentford'), ('BRIGHTON_&_HOVE_ALBION', 'Brighton & Hove Albion'), ('BURNLEY', 'Burnley'), ('CHELSEA', 'Chelsea'), ('CRYSTAL_PALACE', 'Crystal Palace'), ('EVERTON', 'Everton'), ('FULHAM', 'Fulham'), ('LIVERPOOL', 'Liverpool'), ('LUTON_TOWN', 'Luton Town'), ('MAN_CITY', 'Man City'), ('MAN_UTD', 'Manchester Utd'), ('NEWCASTLE_UTD', 'Newcastle Utd'), ('NOTTINGHAM_FOREST', 'Nottingham Forest'), ('SHEFFIELD_UTD', 'Sheffield Utd'), ('TOTTENHAM_HOTSPUR', 'Tottenham Hotspur'), ('WEST_HAM_UTD', 'West Ham Utd'), ('WOLVERHAMPTON_WANDERERS', 'Wolverhampton Wanderers')], default='', max_length=24),
        ),
    ]
